[pytest]

# Ignore heavy integration tests
norecursedirs =
    src/airsim_control
    src/automatic_drive_deep_learning
    src/autonomous_vehicle_navigation_using_dl
    src/object_tracking_planning
    src/yolo12_object_detection
    src/mechanical_arm
    src/humanoid_balance
    src/lane_path_detection
    src/uav_navigation

# Only run lightweight tests
testpaths =
    tests
